
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/casadocodigo-db
    username: jaine
    password: 123456
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    generate-sql: true

